#!/bin/bash

update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
update-alternatives --install /usr/bin/vi vi /usr/local/bin/vim 1
update-alternatives --set editor /usr/local/bin/vim
update-alternatives --set vi /usr/local/bin/vim
