#!/bin/bash

# check current formatting (files have to be formated like in curent .clang-format file)
# use .clang-format file

# WARNING change exclude_* on needed values

find . -type d \( -path '*/build*' -o -path '*/third*' -o -path '*/exclude_dir' \) -prune -o -type f \( ! -iname 'exclude_file' \) -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' -exec cat {} \; | diff -u <(find . -type d \( -path '*/build*' -o -path '*/third*' -o -path '*/exclude_dir' \) -prune -o -type f \( ! -iname 'exclude_file' \) -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' -exec clang-format -style=file {} \;) -
