#!/bin/bash
# Avaliable for Ubuntu (16, 18) and Debian (9)

FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# here all added packages
PACKAGES=""

if [ $# -eq 1 ]; then
  case $1 in
    --help|-h)
      echo 'Supported flags:'
      echo '    --min      | -m : minimal installation (compilers, programming soft)'
      echo '    --full     | -f : full installation (compilers, programming soft, qt, cross environment, virtualbox), but without settings!'
      echo '    --cross    | -c : install cross environment'
      echo '    --qt            : installation of compilers and latest qt (without programming software)'
      echo '    --vbox          : install virtualbox'
      echo '    --sdl2          : install SDL2'
      echo '    --opencv        : install OpenCV'
      echo '    --settings      : set custom settings'
      echo '\n'
      echo 'by default --min'
      exit 0
      ;;
    --min|-m)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo minimal installation
      PACKAGES="install_base_software.sh install_compilers.sh install_dev_software.sh"
      ;;
    --full|-f)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo full installation
      PACKAGES="install_base_software.sh install_compilers.sh install_dev_software.sh install_qt.sh install_mxe.sh install_virtualbox.sh"
      ;;
    --cross|-c)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo cross inastallation
      PACKAGES="install_mxe.sh"
      ;;
    --qt)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo qt installation
      PACKAGES="install_base_software.sh install_compilers.sh install_qt.sh"
      ;;
    --vbox)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo virtualbox installation
      PACKAGES="install_base_software.sh install_virtualbox.sh"
      ;;
    --sdl2)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo SDL2 installation
      PACKAGES="install_base_software.sh install_sdl2.sh"
      ;;
    --opencv)
      if [ $EUID -ne 0 ]; then
        echo you need start it as superuser
        exit 1
      fi
      echo virtualbox installation
      PACKAGES="install_base_software.sh install_opencv.sh"
      ;;
    --settings)
      if [ $EUID -eq 0 ]; then
        echo Do not install this as root
        exit 1
      fi
      echo set settings
      PACKAGES="set_settings.sh"
      ;;
    *)
      echo type --help or -h for help
      exit 1
      ;;
  esac
elif [ $# -gt 1 ]; then
  echo you can set only one flag
  exit 1
else
  if [ $EUID -ne 0 ]; then
    echo you need start it as superuser
    exit 1
  fi
  echo full installation
  PACKAGES="install_base_software.sh install_compilers.sh install_dev_software.sh"
fi

for arg in $PACKAGES; do
  bash $FILE_DIR/$arg
  if [ $? -ne 0 ]; then
    echo fail install script $arg
    exit 1
  fi
done

echo FINISH
